# To install config:
# 1. Clone the repository: 
# 2. Restore submodules: git submodule update --init --recursive
# 3. Run the souce script: ./.tmux/source.sh

unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Set split commands to | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# Set the base index for windows and panes to 1 (instead of 0)
set -g base-index 1
setw -g pane-base-index 1

# Enable mouse support (clickable panes, windows, resizable panes)
set -g mouse on

# Set the default terminal mode to 256 colors
set -g default-terminal "screen-256color"

# Reload the tmux configuration file with prefix + r
bind r source-file ~/.tmux.conf \; display "Config reloaded!"

# Set the status bar at the bottom
set -g status-position bottom

# ==============
# |    TPM     |
# ==============

# Plugin manager (tpm)
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Color scheme
set -g  @plugin 'wfxr/tmux-power'
set -g @tmux_power_theme 'violet'

run '~/.tmux/plugins/tpm/tpm'
