# To install config:
# 1. Clone the repository: 
# 2. Restore submodules: git submodule update --init --recursive
# 3. Run the souce script: ./.tmux/source.sh

unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Set split commands to | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# Set the base index for windows and panes to 1 (instead of 0)
set -g base-index 1
setw -g pane-base-index 1

# Enable mouse support (clickable panes, windows, resizable panes)
set -g mouse on

# Set the default terminal mode to 256 colors
set -g default-terminal "screen-256color"

# Reload the tmux configuration file with prefix + r
bind r source-file ~/.config/tmux/tmux.conf \; display "Config reloaded!"

# Set the status bar at the bottom
set -g status-position bottom

# vim-tmux-navigator
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|l?n?vim?x?|fzf)(diff)?$'"

bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h' 'select-pane -L'
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j' 'select-pane -D'
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k' 'select-pane -U'
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l' 'select-pane -R'

# ==============
# |    TPM     |
# ==============

# Plugin manager (tpm)
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @resurrect-dir '~/.config/tmux/resurrect'

# Color scheme
set -g  @plugin 'wfxr/tmux-power'
set -g @tmux_power_theme 'violet'

# Treemux
set -g @treemux-tree-client 'nvim-tree'
set -g @treemux-tree-nvim-init-file '~/.config/tmux/plugins/treemux/configs/treemux_init.lua'
set -g @plugin 'kiyoon/treemux'

run '~/.config/tmux/.tmux/plugins/tpm/tpm'
